name: Audio to text

inputs:
    audio_file:
        description: Audio file to parse to text.
        required: false
    output_file:
        description: The output text file.
        required: true
    model:
        description: Model used to parse the audio (google or openai).
        default: google
    delete_audio_file:
        description: Delete audio file at the end of the execution (true or false).
        default: false

runs:
    using: composite
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install dependencies
          shell: bash
          run: sudo apt install ffmpeg

        - name: Install Rust
          shell: bash
          if: ${{ inputs.model }} == 'openai'
          run: pip install setuptools-rust

        - name: Install whisper
          shell: bash
          if: ${{ inputs.model }} == 'openai'
          run: pip install git+https://github.com/openai/whisper.git

        - name: Install requirements
          shell: bash
          run: pip install -r $GITHUB_ACTION_PATH/src/requirements.txt

        - name: Run Python script
          shell: bash
          run: python $GITHUB_ACTION_PATH/src/main.py ${{ inputs.audio_file }} ${{ inputs.output_file }} ${{ inputs.model }}

        - name: Delete audio file
          shell: bash
          if: ${{ inputs.delete_audio_file }} == 'true'
          run: rm -r ${{ inputs.audio_file }}

        - name: Reading output file
          shell: bash
          run: cat ${{ inputs.output_file }} && ls -ls
