name: Audio to text

inputs:
  audio_file:
    description: Audio file to parse to text.
    required: true
  output_file:
    description: The output text file.
    required: true
  model:
    description: Model used to parse the audio (google or openai).
    default: google

runs:
  using: composite
  steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: sudo apt install ffmpeg

    - name: Install requirements
      shell: bash
      run: pip install -r $GITHUB_ACTION_PATH/src/requirements.txt

    - name: Run Python script
      shell: bash
      run: python $GITHUB_ACTION_PATH/src/main.py ${{ inputs.audio_file }} ${{ inputs.output_file }} ${{ inputs.model }} 

    - name: Reading output file
      shell: bash
      run: ls -la && cat ${{ inputs.output_file }}
